function this = vc_visualConnectograms( ...
    adjacencyMatrix, ...
    cmap, ...
    areaNames, ...
    wmax, ...
    nodeText, ...
    stimulatedMask)
% VC_VISUALCONNECTOGRAMS
%
% Draw a directed visual-cortex connectogram.
%
% Inputs
% ------
% adjacencyMatrix : N x N matrix
%     Number of significant responses from source area i
%     to recording area j.
%
% cmap : N x 3 matrix
%     Area colors.
%
% areaNames : 1 x N cell array
%     Visual-area labels.
%
% wmax : scalar
%     Maximum response count used for the common line-width scale.
%
% nodeText : 1 x N string array
%     Text displayed within each non-source node.
%
% stimulatedMask : 1 x N logical array
%     True for areas that were actually stimulated in this panel.
% Aug 2026
% Authors: Maria Guadalupe Yanez Ramos (MGYR) and Dora Hermes (DH). 

%% Validate inputs

N = size(adjacencyMatrix,1);

assert(size(adjacencyMatrix,2) == N, ...
    'adjacencyMatrix must be square.');

assert(numel(areaNames) == N, ...
    'areaNames must contain one name per matrix row.');

assert(size(cmap,1) == N, ...
    'cmap must contain one color per area.');

if nargin < 5 || isempty(nodeText)
    nodeText = strings(1,N);
end

if nargin < 6 || isempty(stimulatedMask)
    stimulatedMask = false(1,N);
end

nodeText = string(nodeText(:))';
stimulatedMask = logical(stimulatedMask(:))';


%% Figure and axes

h = figure( ...
    'Color', 'w', ...
    'Position', [100 100 720 720]);

ax = axes('Parent', h);

hold(ax, 'on')
axis(ax, 'equal')
axis(ax, 'off')

set(ax, ...
    'SortMethod', 'childorder', ...
    'Clipping', 'off');


%% Geometry

r_node  = 1.00;
r_label = 1.16;
r_in    = 1.25;
r_out   = 1.40;

thetaCircle = linspace(0, 2*pi, 720);

% Node angles.
t = linspace(0, 2*pi, N+1).' + pi*1.01;
t = t(1:N);

pos = [ ...
    r_node*cos(t(:)), ...
    r_node*sin(t(:))];


%% Gray central background

patch( ...
    ax, ...
    r_in*cos(thetaCircle), ...
    r_in*sin(thetaCircle), ...
    [0.62 0.62 0.62], ...
    'EdgeColor', 'none');


%% Colored stream sectors

% Boundaries derived from the known area ordering:
%
% 1:3   early visual
% 4:9   ventral
% 10:13 lateral
% 14:22 dorsal

areaStep = 2*pi/N;

sectorBounds = [ ...
    t(1)  - areaStep/2, ...   % before V1
    t(4)  - areaStep/2, ...   % between V3 and hOc4v
    t(10) - areaStep/2, ...   % between A37a and TO2
    t(14) - areaStep/2, ...   % between LO1 and V3A
    t(1)  - areaStep/2 + 2*pi];

sectorNames = { ...
    'early visual', ...
    'ventral', ...
    'lateral', ...
    'dorsal'};

% Approximate paper colors.
sectorColors = [ ...
    0.95 0.58 0.45; ...   % early visual
    0.53 0.78 0.65; ...   % ventral
    0.68 0.59 0.76; ...   % lateral
    0.45 0.65 0.88];      % dorsal

for s = 1:4

    th = linspace( ...
        sectorBounds(s), ...
        sectorBounds(s+1), ...
        160);

    sectorX = [ ...
        r_in*cos(th), ...
        r_out*cos(fliplr(th))];

    sectorY = [ ...
        r_in*sin(th), ...
        r_out*sin(fliplr(th))];

    patch( ...
        ax, ...
        sectorX, ...
        sectorY, ...
        sectorColors(s,:), ...
        'FaceAlpha', 0.40, ...
        'EdgeColor', 'none');

end


%% Circular outlines

plot( ...
    ax, ...
    r_node*cos(thetaCircle), ...
    r_node*sin(thetaCircle), ...
    'Color', 'k', ...
    'LineWidth', 1.2);

plot( ...
    ax, ...
    r_in*cos(thetaCircle), ...
    r_in*sin(thetaCircle), ...
    'Color', 'k', ...
    'LineWidth', 1.2);

plot( ...
    ax, ...
    r_out*cos(thetaCircle), ...
    r_out*sin(thetaCircle), ...
    'Color', 'k', ...
    'LineWidth', 1.5);


%% Draw connections first so nodes remain on top

[I,J] = find(abs(adjacencyMatrix) > 0);

w = abs(adjacencyMatrix( ...
    sub2ind([N N], I, J)));

wmin = 1;

if isempty(w)

    alpha = [];

elseif wmax <= wmin

    alpha = zeros(size(w));

else

    alpha = (w - wmin) ./ (wmax - wmin);

end

% Prevent values outside the intended graphical scale.
alpha = max(0, min(1, alpha));

% 
% Common multiplier for all connectogram edges.
% 2.0 = double; 3.0 = triple.
lineWidthMultiplier = 2.5;

baseLineWidth = 0.8 + alpha*(6.0 - 0.8);

LW = lineWidthMultiplier .* baseLineWidth;

R = r_node;
Ri = 0.20;

hEdges = gobjects(numel(I),1);

for edgeIdx = 1:numel(I)

    i = I(edgeIdx);
    j = J(edgeIdx);

    Pi = pos(i,:);
    Pj = pos(j,:);

    % Start and end near the node borders.
    rpad = 0.10*R;

    Pi = (R-rpad) * Pi/norm(Pi);
    Pj = (R-rpad) * Pj/norm(Pj);

    % Curvature control point.
    v = [ ...
        cos(t(i)) + cos(t(j)), ...
        sin(t(i)) + sin(t(j))];

    if norm(v) < eps
        tc = t(i) + pi/2;
    else
        tc = atan2(v(2), v(1));
    end

    C = [ ...
        Ri*cos(tc), ...
        Ri*sin(tc)];

    s = linspace(0,1,100).';

    Qb = ...
        (1-s).^2 .* Pi + ...
        2*(1-s).*s .* C + ...
        s.^2 .* Pj;

    Qr = ...
        (1-s).*Pi + ...
        s.*Pj;

    Q = 0.5*Qr + 0.5*Qb;

    % Edge color identifies the stimulated/source area.
    edgeColor = cmap(i,:);

    hEdges(edgeIdx) = plot( ...
        ax, ...
        Q(:,1), ...
        Q(:,2), ...
        'Color', edgeColor, ...
        'LineWidth', LW(edgeIdx));

end


%% Draw nodes and internal annotations

hNodes = gobjects(N,1);
hNodeText = gobjects(N,1);
hAreaText = gobjects(N,1);

for i = 1:N

    xi = pos(i,1);
    yi = pos(i,2);

    hNodes(i) = plot( ...
        ax, ...
        xi, ...
        yi, ...
        'Marker', 'o', ...
        'MarkerSize', 40, ...
        'MarkerFaceColor', cmap(i,:), ...
        'MarkerEdgeColor', [0.25 0.25 0.25], ...
        'LineWidth', 0.5);

    if stimulatedMask(i)

        % Default upward arrow rotated toward the center.
        arrowRotation = mod(rad2deg(t(i)) + 90, 360);

        hNodeText(i) = text( ...
            ax, ...
            xi, ...
            yi, ...
            char(8593), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'Rotation', arrowRotation, ...
            'Color', 'k', ...
            'FontSize', 17, ...
            'FontWeight', 'bold', ...
            'Interpreter', 'none');

    elseif strlength(nodeText(i)) > 0

        hNodeText(i) = text( ...
            ax, ...
            xi, ...
            yi, ...
            char(nodeText(i)), ...
            'HorizontalAlignment', 'center', ...
            'VerticalAlignment', 'middle', ...
            'Color', 'k', ...
            'FontSize', 9, ...
            'FontWeight', 'normal', ...
            'Interpreter', 'none');

    end

    % Tangential area label.
    areaRotation = rad2deg(t(i)) - 90;

    hAreaText(i) = text( ...
        ax, ...
        r_label*cos(t(i)), ...
        r_label*sin(t(i)), ...
        areaNames{i}, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'Rotation', areaRotation, ...
        'Interpreter', 'none', ...
        'Color', 'k', ...
        'FontSize', 11);

end


%% Stream boundaries

for s = 1:4

    th = sectorBounds(s);

    plot( ...
        ax, ...
        [r_node*cos(th), r_out*cos(th)], ...
        [r_node*sin(th), r_out*sin(th)], ...
        'Color', 'k', ...
        'LineWidth', 1.5);

end


%% Stream labels

for s = 1:4

    thCenter = ...
        (sectorBounds(s) + sectorBounds(s+1))/2;

    rText = (r_in + r_out)/2;

    xText = rText*cos(thCenter);
    yText = rText*sin(thCenter);

    textRotation = rad2deg(thCenter) - 90;

    text( ...
        ax, ...
        xText, ...
        yText, ...
        sectorNames{s}, ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'Rotation', textRotation, ...
        'Color', 'k', ...
        'FontSize', 14, ...
        'FontWeight', 'bold', ...
        'Interpreter', 'none');

end


%% Final axes limits

axis(ax, [ ...
    -1.48 1.48 ...
    -1.48 1.48]);


%% Return useful handles and metadata

this = struct;

this.Figure = h;
this.Axes = ax;
this.Node = hNodes;
this.NodeText = hNodeText;
this.AreaText = hAreaText;
this.Edges = hEdges;
this.ColorMap = cmap;
this.Label = areaNames;
this.StimulatedMask = stimulatedMask;
this.DisplayText = nodeText;

end